### PR TITLE
Reformat code and organized script folder

### PR DESCRIPTION
**Pull request by KS-103819380**
Reformatted code according to this: https://docs.google.com/document/d/1ngzQ6UUjyCyknk-3t2Rl_pwRQeF-trg98L_ouxy9t1c/edit#heading=h.wkccxurzibci

### CODE REVIEW

**Comment by GhostEntity12** [comment]
Lots of merge conflicts that need solving

**Comment by KS-103819380** [comment]
Can you merge all the other branches first? Even if I solve it now it will be more troublesome when u try to merge other branches.

**Comment by GhostEntity12** [comment]
#38 has conflicts of it's own. Not my place to fix that one. Will resolve #28

**Comment by GhostEntity12** [comment]
#28 finally resolved, #38 is the only open PR now. You shoould be good to go. Once solved, please tag all of the programmers to update their branches and work, and to follow the new conventions. I'll make sure they follow them in PR reviews.

**Review by GhostEntity12 — APPROVED** [review]

**Comment by GhostEntity12** [comment]
@KS-103819380 Checking whether this branch can be deleted

**Comment by KS-103819380** [comment]
yea sure go ahead

**Pull request merged**
