### PR TITLE
Volume sliders

### PR DESCRIPTION
**Pull request by SassDude**
added code so that the volume settings save between playthrough, linked up the volume sliders to the audio manger in the scene

### CODE REVIEW

**Review by AdmiralSoviet — CHANGES_REQUESTED** [review]
Can't approve.
- adjusting the sliders doesn't affect the sound at all while inside the house, only in hunting.
- music is tied to sound effects instead of music volume
- please remove the strike-through on the text in the settings to indicate the sliders work

**Comment by GhostEntity12** [comment]
Merging of #57 also introduced merge conflicts that need to be resolved.

**Comment by SassDude** [comment]
fixed

**Review by AdmiralSoviet — APPROVED** [review]
The settings till dont affect the music inside the house and the number on the volume slider needs to have rounded decimals, but I reckon turning these into separate cards is preferred at this point.

**Pull request merged**
