### PR TITLE
Implement new furniture

### PR DESCRIPTION
**Pull request by Waltzerr**
-New furniture and environment models
-New models and furniture implemented for:
+Table
+Bed
+Plate
+Cup
+Cactus
+Lamp
+Lamp Shade
+Wardrobe

### CODE REVIEW

**Review by GhostEntity12 — CHANGES_REQUESTED** [review]
Please ensure that the meshes are named according to the naming conventions. This goes for both the furniture and environment meshes.

**Comment by GhostEntity12** [comment]
Conflicts resolved. @Waltzerr Please make requested changes ASAP as other pull requests may depend on this.

**Review by Waltzerr — COMMENTED** [review]
Files have been renamed according to naming conventions

**Review by GhostEntity12 — APPROVED** [review]
Will work for now. However, should discuss in detail about whether the naming conventions should be changed. Technically, `Furniture_dumbell_001`, `Furniture_Arcade Machine` and more don't strictly follow the naming conventions

**Pull request merged**
