### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by KS-103819380**

### CODE REVIEW

**Comment by GhostEntity12** [comment]
What were the changes made in this commit?

**Comment by KS-103819380** [comment]
> What were the changes made in this commit?

which commit are you referring to?

**Comment by GhostEntity12** [comment]
Nevermind, didn't look at the individual commits properly.

**Review by GhostEntity12 — CHANGES_REQUESTED** [review]
Looks like the inventory cannot currently be opened in the hunting scene

**Comment by KS-103819380** [comment]
@GhostEntity12. Should be fixed now

**Review by GhostEntity12 — APPROVED** [review]

**Pull request merged**
