### PR TITLE
Weapon manager refactor

### PR DESCRIPTION
**Pull request by GhostEntity12**
Untangles the weapons from the save system

# Primary changes
- `WeaponManager` has been significantly overhauled
- `Gun` has been significantly overhauled
  - The `shooting`, `readyToShoot` etc. bools have been replaced with a `GunState` enum
  - `IEnumerators` have been replaced with `Invoke`
- A new `AmmoPouch` class is stored on each gun and keeps track of that gun's ammunition 
- Weapons are no longer part of the save system, other than whether they are unlocked
  - A new struct called `SaveDataGun` keeps track of the ID of the saved gun and can be looked up from `DataPersistenceManager`
  - The bullet scriptable objects have been removed

# Other changes
- The shop has been disabled, though the code still exists
  - `ShopItem` and `GunShopItem` have been removed
- `GameData` no longer saves the hunting inventory or the bought items, and now saves guns
- Saveable structs have been renamed to be clearer
  - `InventoryItem` → `SaveDataFurniture`
  - `HouseItem` → `SaveDataPlacedFurniture`
- `Inventory` has been replaced by `FurnitureInventory` and no longer has the ability to store items other than furniture

### CODE REVIEW

**Comment by KS-103819380** [comment]
I wanted to test this, but encountered the following:
- Weapon wheel is broken
- The game does not select a gun when starting the hunting scene

Is there a reason for the refactor? I briefly read through the code, shop will probably no longer work even after you re-enable it again as it depends on `ShopItem`. I structured the code like this initially so that we could have different number of weapons according to what the player has bought. It also allows player to buy consumables (but I guess that would be irrelevant now since we are not implementing the feature).

**Comment by GhostEntity12** [comment]
Reason for rework was due to complaints from other members of the team that the systems were too interconnected and confusing, requiring a lot of jumping between different scripts to implement new behaviours. Changes to the game's design also meant several parts of the code could be simplified, including save requirements being clarified, no longer requiring ammunition numbers to be saved, and the shop being removed.

Will retest the raised issues - there may have been changes I had on a different branch that I didn't commit to this PR.

**Comment by GhostEntity12** [comment]
@KS-103819380 Looks like the issue with the weapon not turning up is the same save issue as previously discussed in Discord. Loading the game once from the main menu resolves the issue.

**Comment by KS-103819380** [comment]
Do not merge yet. Weapon crosshair alignment hasn't been fixed.

**Review by KS-103819380 — APPROVED** [review]

**Comment by KS-103819380** [comment]
@GhostEntity12 I have fixed everything. Ready to merge with main.

**Pull request merged**
